version: 2.1

jobs:
  checkout_And_Unit_Test:
    machine: true
    steps:
      - run: echo "integration_tests_backend"
  integration_tests_backend:
    machine: true
    steps:
      - run: echo "integration_tests_backend"
  deploy_production:
    machine: true
    steps:
      - run: echo "deploy production build"
  acceptances_test_1:
    machine: true
    steps:
      - run: echo "acceptance tests 1-5"
  checkoutAndTest:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run: echo "unit tests"
  acceptances_test_2:
    machine: true
    steps:
      - run: echo "acceptance tests 6-10"
  acceptances_test_3:
    machine: true
    steps:
      - run: echo "acceptance tests 6-10"
  acceptances_test_4:
    machine: true
    steps:
      - run: echo "acceptance tests 6-10"
  deployStaging:
    machine: true
    steps:
      - run: echo "deploy staging"
  deployBackend:
    machine: true
    steps:
      - run: echo "notifying client of new version"
workflows:
  build:
    jobs:
      - checkout_And_Unit_Test
      - deployBackend:
          requires:
            - checkout_And_Unit_Test
      - integration_tests_backend:
          requires:
            - deployBackend
      - deployStaging:
          requires:
            - integration_tests_backend
      - acceptances_test_1:
          requires:
            - deployStaging
      - acceptances_test_2:
          requires:
            - deployStaging
      - acceptances_test_3:
          requires:
            - deployStaging
      - acceptances_test_4:
          requires:
            - deployStaging
      - deploy_production:
          requires:
            - acceptances_test_1
            - acceptances_test_2
            - acceptances_test_3
            - acceptances_test_4
